language: ruby
cache: bundler
sudo: false
rvm:
  - 2.5.1
  - 2.4.4

gemfile:
  - 'gemfiles/sidekiq_4.gemfile'
  - 'gemfiles/sidekiq_5.gemfile'
  - 'gemfiles/sidekiq_6.gemfile'

matrix:
  exclude:
    - rvm: 2.4.4
      gemfile: gemfiles/sidekiq_6.gemfile

deploy:
  provider: rubygems
  api_key:
    secure: "VX48kpd9UySMWSDMwjxaNZy14RW1usU7eFLGNeohjCzxUsCywn+mS5/IZHl56vDXWJp7JwnboDiIa74hGV86PcSEM7kr+DAZO33iCazMNTpoWDiH1iJfj0jZbO2rOvx0rGI9fGYcC9xfyKQ37hVb13Eo0bnKa0YX30HArnx7EFo="
  on:
    tags: true
    all_branches: true
